# Generated by Django 4.2.4 on 2023-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='type_flower',
            field=models.CharField(choices=[('apartment', 'آپارتمانی'), ('garden', 'باغچه ای'), ('ornamental', 'زینتی')], default='garden', max_length=50, verbose_name='نوع گل'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='توضیحات'),
        ),
    ]
