# Generated by Django 4.2.4 on 2023-09-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_flower_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='care',
            field=models.TextField(default='', max_length=10000, verbose_name='شیوه نگهداری'),
        ),
        migrations.AddField(
            model_name='flower',
            name='suitable_weather',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='flower',
            name='water_requirement',
            field=models.CharField(default='', max_length=130),
        ),
    ]
